#!/usr/bin/env python

import sys

from rqt_autonomous_nav.autonomous_nav_module import MyPlugin
from rqt_gui.main import Main

plugin = 'rqt_autonomous_nav'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
